### PR TITLE
Update kotlin gradle plugin to 1.8.10

### PR DESCRIPTION
**Pull request by andreadelfante**
This PR fixes broken builds using a high version of kotlin_version and flutter 3.

Screenshot 2023-03-24 alle 15 35 59

### CODE REVIEW

**Comment by mateusfccp** [comment]
I'm pretty sure I compiled the example with Flutter 3. I am not sure about the Kotlin version, tho. I am going to give a look on this PR as soon as I have some time.

Thanks for the contribution!

**Comment by andreadelfante** [comment]
Hi @mateusfccp, any news about this PR?

**Comment by mateusfccp** [comment]
Hi, @andreadelfante. I tried your PR just right now, and got a problem.

Trying to compile the example, which is set to `ext.kotlin_version = '1.6.10'` will fail on your PR. I only got to compile the example after also updating the example to `1.8.10`.

On the other side, leaving the version the same as it is now (`1.3.50`) will compile perfectly in the example when it's set to `1.8.10`.

It seems that this is not what we want, as we may be forcing the clients of this package to update their Kotlin version unnecessarily, and people who uses more recent Kotlin versions can still compile their app.

I could not reproduce the error you showed in the PR description.

Maybe I am missing something?

**Comment by mateusfccp** [comment]
@andreadelfante I just saw [this page](https://docs.flutter.dev/release/breaking-changes/kotlin-version) that says that, since Flutter 2.10, it's required a Kotlin version of 1.5.31 or greater. I don't know why I can build the example package with a lower version.

Does this solves your problem? Can we upgrade the version to 1.5.31 instead?

**Comment by Jahyrm** [comment]
I just tried, changing:

`ext.kotlin_version = '1.3.50'` to `ext.kotlin_version = '1.5.31'` in the file:

_update_available_android/android/build.gradle_ 

Directly into my repositories and packages cache and my project compiled, so I guess so.

However, I detail the versions that are in my project:

- Flutter version: 3.10.5
- Dart version: 3.0.5
- In my project pubspec.yaml:
`environment:
  sdk: '>=3.0.5 <4.0.0'`
- In my project android/build.gradle:
`ext.kotlin_version = '1.7.10'`

**Comment by mateusfccp** [comment]
Yeah, I think this is the way to go. We want to support the lowest possible version, and it seems that current Flutter requires at least `1.5.31`.

@andreadelfante, could you make this change so we could merge your PR?

**Comment by mateusfccp** [comment]
Also, please bump the Flutter supported version from 2.8 to 2.10 in the packages

**Comment by Jahyrm** [comment]
Hello, as I need this plugin in my project, and I don't see an answer, can I do the PR myself?

**Comment by mateusfccp** [comment]
Superseded by 2a6c617.

**Pull request closed without merging**
